### ISSUE TITLE
Center boards

### ISSUE THREAD

**Issue by jeremejevs** [ZenHubIO/support#574]
I'm really digging ZenHub, but I'd like to have a way to center the columns and/or limit the width of the boards section. Here's what it looks like on a QHD screen:

![](http://i.imgur.com/55XWAXN.png)

Hope it's self-explanatory :)

**Comment by Mottie** [comment]
If you use the Stylish browser addon, you can create a style to set a max-width:

```css
@-moz-document domain("github.com") {
  .zh-board-visible--native .pagehead + .container {
    max-width: 1024px !important;
  }
}
```
