### ISSUE TITLE
Move pipeline label in issue list

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#599]
I think the pipeline label in the issues should be on the right side to make it easier to read. Something like this:

![2016-03-05 17_55_11-issues zenhubio_support](https://cloud.githubusercontent.com/assets/136959/13551410/74e82672-e2fe-11e5-8ff9-ad05ae0a9851.png)

I use this Stylish userstyle to do this for me:

``` css
@-moz-document domain("github.com") {
  .issue-meta {
    position: relative;
  }
  .zh-issue-meta-pipeline {
    position: absolute;
    right: 10px;
  }
  .zh-issue-meta-pipeline .zh-issue-meta-pipeline-icon {
    float: right;
    margin-left: 4px;
  }
}
```
