### ISSUE TITLE
Reaction tooltips breaking

### ISSUE THREAD

**Issue by Mottie** [ZenHubIO/support#623]
GitHub sets their multiline tooltips css definition to `display: table-cell`:

```css
.tooltipped-multiline:hover::after, .tooltipped-multiline:active::after, .tooltipped-multiline:focus::after {
    display: table-cell;
}
```

And the ZenHub extension adds the following:

```css
*, ::before, ::after {
    box-sizing: border-box;
}
```

Which breaks the multiline setting, at least in Chrome, and makes the reaction tooltips very narrow... Hover over the reactions below to see it happen.
